### ISSUE TITLE
Suggestion for README file

### ISSUE THREAD

**Issue by alejandrosantana** [amigrave/git-qdiff#2]
Hi!
Nice work, looks good and it is a nice help.

I would like to suggest to add a little reminder to the documentation (e.g. to the README file):

```
Remember to previously run the command:
bzr whoami "Your Name <name@example.com>"
```

Right after installing, I tried _git qdiff_ and forgot to previously run _bzr whoami_ (just not using my usual laptop) and I got an error. Nothing critical or complicated, but ugly anyways:

_git qdiff
bzr: ERROR: Unable to determine your name.
Please, set your name with the 'whoami' command.
E.g. bzr whoami "Your Name name@example.com"
Traceback (most recent call last):
  File "/usr/local/bin/git-qdiff", line 7, in <module>
    sys.exit(git_qdiff.main())
  File "/usr/local/lib/python2.7/dist-packages/git_qdiff.py", line 54, in main
    qdiff(left, right)
  File "/usr/local/lib/python2.7/dist-packages/git_qdiff.py", line 16, in qdiff
    subprocess.check_call(['bzr', 'commit', '-qmm'])
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['bzr', 'commit', '-qmm']' returned non-zero exit status 3
/usr/lib/git-core/git-difftool line 464: No existe el archivo o el directorio
git failed with returncode 1_

**Comment by amigrave** [comment]
Thanks !
